### ISSUE TITLE
Crystals not dropping with tool

### ISSUE THREAD

**Issue by ghost** [jaredlll08/Fluxed-Crystals-Reborn#15]
When using a Scythe the crystals do not drop anything, ever.  When using empty hand they work fine.

**Comment by ghost** [comment]
Need to look at balance, I seem to get a high chance of drops with the empty hand now than the wooden tool.  The iron is also a little short on drops compared to the almost always with diamond.

**Comment by jaredlll08** [comment]
Yea... the code looks sound :/ I have no idea why it isn't calling it..
