### ISSUE TITLE
Shift Click crash

### ISSUE THREAD

**Issue by dmaster8** [jaredlll08/Fluxed-Crystals-Reborn#18]
So i try shift click rough shards into the gem refiner I crash. I know the recipe isn't to put rough shards into the gem refiner it happened by accident. http://pastebin.com/kXJbpqzD

**Comment by ghost** [comment]
are you using a release or did you compile the latest code?

**Comment by dmaster8** [comment]
Jared compiled the latest code for me :P

**Comment by ghost** [comment]
ok let me give it a look

**Comment by ghost** [comment]
Ok I just tested on the latest code and there isn't a crash and the shift click is handled correctly.  I am going to assume you might have some old code.  @jaredlll08 can you get him a new build please?

**Comment by dmaster8** [comment]
It might be because i'm using custom seeds?

**Comment by ghost** [comment]
that shouldn't be an issue lets test on the latest code once he gets that to you and see from there

**Comment by dmaster8** [comment]
It still crashes

**Comment by ghost** [comment]
ok get the latest one now and check, if that crashes post your master seed json so I can take a look
