### ISSUE TITLE
[1.0.2] Gem refiner not craftable

### ISSUE THREAD

**Issue by iarspider** [jaredlll08/Fluxed-Crystals-Reborn#20]
NEI doesn't show a recipe to craft Gem Refiner.

**Comment by jaredlll08** [comment]
Is it actually craft able though?

**Comment by iarspider** [comment]
It works if I cheat it in, if that's what you are asking.

**Comment by jaredlll08** [comment]
It wasn't but I think I got it sorted, thanks

**Comment by jaredlll08** [comment]
Fixed in 1.0.3
