### ISSUE TITLE
Json write issue v1.0.3

### ISSUE THREAD

**Issue by Blargerist** [jaredlll08/Fluxed-Crystals-Reborn#21]
Whenever the mod re-writes the masterSeedData.json file it appears to be doing it ever so slightly wrong, and causing a crash the next time you try to start up the mod. The bit of bad Json:

{"seeds":[,{

This is the first line, you may notice that the 11th character is a comma, which is not somewhere that a comma should be. Removal of the comma causes the config to be read properly, and not crash the game.

**Comment by jaredlll08** [comment]
I have not experienced this problem, and I spent a good hour editing FC jsons...

**Comment by Blargerist** [comment]
I believe I may have found the issue, assuming I properly understand your code. I apologize if I am incorrect.

In this method: https://github.com/jaredlll08/Fluxed-Crystals-Reborn/blob/master/src/main/java/fluxedCrystals/util/JsonTools.java#L20 you loop through a map and only add a comma if the Integer key is > 0. Is the Integer key perhaps based the seedID field in the config? If so, the problem I am experiencing is caused by the fact I start the ids of the seeds in my config at 1 rather than 0. 

EDIT: I attempted adding a random seed with ID 0, and it appears to no longer break itself.

**Comment by Blargerist** [comment]
On line 26:

if (i > 0) {

may perhaps want to omit the first entry rather than the entry with key 0 with something like:

boolean doneFirst = false;

if (doneFirst)
{
tmpString += ",";
}else
{
     doneFirst = true;
}

**Comment by jaredlll08** [comment]
Well IDs should ALWAYS be in chronological order, so I don't really see the need to fix this. if you do, then please re-open the issue and we can talk.

**Comment by superckl** [comment]
If I'm not mistaken, you are not required to include an ID of 0. Even if the IDs were in ascending order, it would break in that case.

**Comment by jaredlll08** [comment]
I think you got confused. You NEED a ID at 0 the rest I guess can be any
order, but there MUST be a 0

**Comment by superckl** [comment]
My bad then. I still hold that this should be fixed, though. If someone desires to order their config in another way, say by name or something, breakage will occur.

**Comment by superckl** [comment]
Why is a 0 id required? The mod appears to run fine without a 0, it's just the config rewrites itself incorrectly.

**Comment by jaredlll08** [comment]
It is 0 so that there is a starting point, we start counting from 0, honestly, you should ask @JHarb52207 more about this. and the json can be written in any order, just as long as there is a value at 0.
I don't see a reason for there not to be a zero value anyway...

**Comment by Blargerist** [comment]
Here's a config without id 0, it works perfectly fine as far as I can tell... once. After closing, the json writer gets confused by the lack of id 0, and adds a comma in the wrong place, breaking the json and stopping the config from being read when loaded the next time. https://gist.github.com/Blargerist/3ab92581241dd3a74a9b

The reason for a person to not add a 0 id, is that everyone doesn't think like a java developer, numbers  tend to start at 1 for those weird normal people. :P

**Comment by jaredlll08** [comment]
Ok well I have fixed it using your method, so all blame is on you! (jk jk :3)
anyway, we actually add a command to automatically generate a template seed with the next / missing ID.
/fluxedcrystals seed-from-current
also 
/fluxedcrystals seed-editor

**Comment by Blargerist** [comment]
Holy ***\* those commands are useful. Particularly the seed editor. Wish I had found that during my attempts to find documentation on how to do the configs for this mod.

Ps: Ty for the fix. <3

**Comment by jaredlll08** [comment]
Np :)

**Comment by jaredlll08** [comment]
On further review, your code failed to work, like I have been saying, I don't even see a need to change it. if @JHarb52207 would like to, then he is free to.

**Comment by Lunatrius** [comment]
You could just use GSON for the entire thing...

```
public static String hashmapToJson_seeds (HashMap<Integer, Seed> seedMap) {
  HashMap<String, List<Seed>> map = new HashMap<String, List<Seed>>();
  map.put("seeds", seedMap.getValues());
  return gson.toJson(map, new TypeToken<HashMap<String, List<Seed>>>() {}.getType());
}

public static List<Seed> jsontoList_seeds (String content) {
  HashMap<String, List<Seed>> map = gson.fromJson(content, new TypeToken<HashMap<String, List<Seed>>>() {}.getType());
  List<Seed> seeds = map.get("seeds");
  if (seeds == null) {
    return new ArrayList<Seed>();
  }

  return seeds;
}
```

I haven't tested it, but should work.

As for why the "fix" didn't work, [this](https://github.com/jaredlll08/Fluxed-Crystals-Reborn/blob/dfbc6faba2a189e14d918a36d9493b685ddaff10/src/main/java/fluxedCrystals/util/JsonTools.java#L25) should've been above the for loop. Like that it's just a local variable that's initialized to false every time.
