### ISSUE TITLE
Fluxed-Crystals2-1.0.2 crash on harvesting diamond crop

### ISSUE THREAD

**Issue by plazia** [jaredlll08/Fluxed-Crystals-Reborn#22]
Had a crash this morning while harvesting a diamond crop.

Crash report here. http://pastebin.com/0RYkpS68

**Comment by ghost** [comment]
Well that one looks like a fun time, can you send a screen shot of that area pre-harvest?

**Comment by jaredlll08** [comment]
oh I think I fixed this one xD forgot to say anything. try with 1.0.3 on curse
