### ISSUE TITLE
Help with configs

### ISSUE THREAD

**Issue by Anomerly** [jaredlll08/Fluxed-Crystals-Reborn#23]
I am looking for help with configs, is this a good place to ask for help? My problem is tricky because it doesn't actually involve a crash, instead the infuser just seems to be ignoring (or at the very least not providing any feed back) to what its problem is.

The issue I am having is the infuser doesn't seem to work for any of vanilla items as well as several of the mod based items.

Thaumic Shards work as do Fluix crystals, but Skystone doesn't... Clearly I have got something wrong, but I am struggling to figure out what.

Here is the config I have cobbled together so far, I haven't finished colouring my seeds, but it is mostly finished.
https://drive.google.com/file/d/0B87rOGGblz9DRW5Bdm85eHBCQUk/view?usp=sharing

Any help or suggestions would be greatly appreciated,

**Comment by ghost** [comment]
Do the seeds appear in NEI as available with this config?

When using the infuser are you putting the correct amount of the ingredient in as well?

What about shards, are they generating in NEI and able to be used in the machines?

**Comment by Anomerly** [comment]
The seeds, their rough and smooth shards and associated tools all appear in NEI as they should.
I am putting in the amount specified in the config, or more into the infuser, as I said I have created a few of the Mod Items, Tin works with both dictionary entries, but skystone doesn't.

All recipes seem to work fine through the Gem Cutter and the Gem Refiner.
It is just the infuser that seems to be having trouble.

I am pretty confident that what ever I am doing wrong is in the config rather than the game.

**Comment by ghost** [comment]
Hmm,

@jaredlll08 can you take a look at this and see if there is something in the config I am missing, might be that ore dict thingy again as well

**Comment by Anomerly** [comment]
I suspect it is to do with the item naming convention in the 'ingredient' and 'weightedDrop' fields, though I am not sure why this would stop the Infuser and not the Refiner.

To be clear here is an example:
Sample script uses: dustRedstone
Mine calls it: minecraft:redstone

I have been getting the naming out of NEI's CSV dump functions as that is the only way I know to get the 'Real' names of the game objects, also it keeps them consistent with the naming conventions used in mod introduced items.

**Comment by jaredlll08** [comment]
hhm, I always use oredict when possible, it is just much easier, also, the refiner does different things than the infuser, in regards to figuring out the itemstack, could you try oredict?

**Comment by Anomerly** [comment]
How do I get the list of ore dictionary names? (Including Mod added items)
The way I am getting names is through the CSV dump functions in NEI and this is what it gives me.
Is there some way of dumpling a listing from my mod pack to a file?

Also, I correct me if i am wrong but I should only have to change the 'ingredient' field as it is the one looked at by the infuser.

**Comment by jaredlll08** [comment]
Yea, ingredient is used by both, also, iirc Nei Integration has extra dumps, that allow oredict

**Comment by Anomerly** [comment]
I found the ore dictionary, so if both look to the ingredient field what is the weightedDrop field for? I assumed one was infuser requirement and the other what the seed produced (and if left blank they were the same.)

Unfortunately not everything in my list appears to be in the ore dictionary. minecraft:cactus or minecraft:pumpkin are two examples I found so far.

**Comment by jaredlll08** [comment]
Well just try some of the things that do not work, for instance the sky stone

**Comment by Anomerly** [comment]
Ok ore dictionary entries work fine, so that will fix most everything in my list, and I can drop items that can be grown other ways such as cactus and pumpkin, but I did have high hopes for the Sky Stone.

**Comment by jaredlll08** [comment]
So, it works now? (I know not a fix, I will code in a fix though)

**Comment by Anomerly** [comment]
It has fixed more than half of the items in my config, (all the ores) There is a dozen plants and mod items that have just not been registered in the ore dictionary, mod added items some work others don't, not sure why.
Vanilla items not registered in the ore dictionary (mostly mob drops) just don't work.

If I can't fix it in the config, can you fix that in the mod?

**Comment by jaredlll08** [comment]
Yea

**Comment by jaredlll08** [comment]
I suggest using minetweaker to add oredicts
