### ISSUE TITLE
Do the automation upgrades work?

### ISSUE THREAD

**Issue by cauliflower69** [jaredlll08/Fluxed-Crystals-Reborn#28]
I have attempted to add automation upgrades to the powered soil to automate the seeds as I was using Autonomous Activators before. They do not seem to break and replant themselves

**Comment by jaredlll08** [comment]
That is extremely weird, what version are you using? because recently someone showed me a build using the automation upgrades

**Comment by cauliflower69** [comment]
We are using a slightly outdated build but I have also updated to the latest and had the same issue. Maybe I'm missing some key to getting them working ?

Place powered soil, right click with the automation upgrade, add power and add seed is the way I assume it works ?

On a side note what does the enderio support option allow in the cfg?

Finally, why can the soil take up to three automation upgrades ?

Thanks for the feedback

**Comment by jaredlll08** [comment]
ok this is extremely weird, it is working fine for me :/ how are you powering the soil? also there are other upgrades, speed and efficiency
speed makes stuff grow faster
and efficiency uses less energy.

**Comment by jaredlll08** [comment]
can not replicate.
