### ISSUE TITLE
[Question]Can I download latest seeds information from this github inside a computercraft program I'm writing?

### ISSUE THREAD

**Issue by Stekeblad** [jaredlll08/Fluxed-Crystals-Reborn#32]
Hi, I am working on a Computercraft program for automating the refining of smooth shards with only one refiner and got the idea to implement a function that downloads the latest seed information from this github for the program to use.

Is this ok for you?

More then just downloading seed data, it will also be possible to add, remove and edit  seeds in the programs seeds table manually if a users config file differs from the default one.

**Comment by jaredlll08** [comment]
If you can do that, then go ahead :)
