### ISSUE TITLE
Serious FPS drops

### ISSUE THREAD

**Issue by LokeYourC3PH** [jaredlll08/Fluxed-Crystals-Reborn#35]
So, i don't have any logs for this, but all players on my server notice this. Their base can have a lot of machines, but they still stay above a 100 FPS, but once they place the Gem Cutters and Gem Refiners from Fluxed Crystals 2, they cause everyone's FPS to drop at least to 50 FPS or below, which is a lot. We also noticed that it is not just the Machines that cause this, but also the Powered Soil and the Seeds that are on top of the Powered Soil itself. They also seem to cause FPS drops, and i guess either due to the Automation Upgrade, or the Custom Seeds. Either way, it is somewhat annoying, considering that building it in a base is almost useless, as you just drop to much in FPS, including the FPS drops from all the other machines from other mods. Could this be looked into please?

Also: We do know its Fluxed Crystals 2, as we have our FPS counter up, and if we for example open the Gem Cutter or Gem Refiner interface, our FPS drops from already low 40 to 25 or even LOWER. Yes, it is Fluxed Crystals 2, no doubt.

**Comment by ghost** [comment]
Sorry to hear this is happening, unfortunately your the first and only person to ever report FPS drops with the mod.  FPS counters wouldn't be a great indicator since mods can interact with each other and there could be many things causing this issue.  I would suggest gathering some additional information such as with Opis and confirm the issue.  Also logs could help as well from both the client and server side.

**Comment by LokeYourC3PH** [comment]
Funny that you mention OPIS, because i had to throw that mod off my server after it has become so outdated, that it caused problems with other mods (it was the MapWriter part of OPIS). So OPIS is a no go (and it hasn't been updated for a LONG time now from ProfMobius).

I don't know about any logs i could provide, so you tell me.

**Comment by LokeYourC3PH** [comment]
Also, with FPS Counter, i mean the in-game Minecraft one that you open with F3.
