### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by Nincodedo** [jaredlll08/Fluxed-Crystals-Reborn#4]
Running Fluxed Crystals 1.0.0. Runs fine just on my client but crashes when I try to start my server.

http://pastebin.com/1a1s7Lcr

**Comment by ghost** [comment]
What modpack are you using?

**Comment by Nincodedo** [comment]
Custom pack I've put together with a friend. The repo for it can be found here https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen

**Comment by ghost** [comment]
@jaredlll08 think I found the issue, looks like a client only event made it into a server handler.  Fixing

**Comment by ghost** [comment]
I just uploaded the 1.0.2 release to github here, please give that a try

**Comment by Nincodedo** [comment]
I'm getting this error now when trying to load my world. http://pastebin.com/igrsKGxT It loads fine with a new world.

**Comment by ghost** [comment]
Yep I saw that in our existing test world, there were some other changes in the 1.0.1 release that causes those.  @jaredlll08 can you look at that in the AM and see if you can get the 1.0.2 code to upgrade cleanly instead of losing all the tiles in an existing world?  That aside I think the original issue you reported sounds solved with this build we just need to look into that other matter.

Thanks

**Comment by jaredlll08** [comment]
I will look into it today

**Comment by jaredlll08** [comment]
I believe this has been fixed, please try with 1.0.1

**Comment by Nincodedo** [comment]
Where can I find 1.0.1? There's a 1.0.0 and 1.0.2 in the releases.

**Comment by jaredlll08** [comment]
on curse :P

**Comment by Nincodedo** [comment]
Still crashing http://pastebin.com/vY45dYF6

**Comment by jaredlll08** [comment]
dammit will have a fix up later

**Comment by jaredlll08** [comment]
Fixed, tested it myself

**Comment by Nincodedo** [comment]
This has not been fixed as of v1.0.2 on the CurseForge page. http://pastebin.com/pm4UwSTK

**Comment by Nincodedo** [comment]
This has not been fixed as of v1.0.3 on the CurseForge page. http://pastebin.com/dffzvRfP

**Comment by jaredlll08** [comment]
Unfortunately, I think  you are going to need to make a new world. Sorry.
